# Generated by Django 3.0.8 on 2020-10-19 21:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='display',
            field=models.BooleanField(null=True),
        ),
        migrations.AlterField(
            model_name='category',
            name='display_in_home',
            field=models.BooleanField(null=True),
        ),
        migrations.AlterField(
            model_name='category',
            name='order',
            field=models.PositiveSmallIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='color',
            name='hex_code',
            field=models.CharField(max_length=7),
        ),
    ]
