# Generated by Django 3.0.8 on 2020-10-20 00:27

from django.db import migrations, models
import stdimage.models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_auto_20201019_1913'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='code',
            field=models.CharField(max_length=6, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='image',
            field=stdimage.models.StdImageField(null=True, upload_to='images'),
        ),
        migrations.AlterField(
            model_name='product',
            name='order',
            field=models.PositiveSmallIntegerField(null=True),
        ),
    ]
